#!/usr/bin/env python

# Run script of the qsvm testing. See the test.py file for more details 
# on how it works.

import argparse
import json

from test import main


parser = argparse.ArgumentParser(formatter_class=argparse.
                                 ArgumentDefaultsHelpFormatter)
parser.add_argument("--sig_path", type=str, required=True,
                    help="Path to the signal/anomaly dataset (.h5 format).")
parser.add_argument("--bkg_path", type=str, required=True,
                    help="Path to the QCD background dataset (.h5 format).")
parser.add_argument("--test_bkg_path", type=str, required=True,
                    help="Path to the background testing dataset (.h5 format).")
parser.add_argument('--backend_name', type=str,
                    help='The IBM backend. Could be a simulator'
                    ', noise model, or a real quantum computer')
parser.add_argument('--run_type', type=str, required=True,
                    choices=['ideal', 'noisy', 'hardware'],
                    help='Choose way to run the QSVM: Ideal computation,'
                    'noisy simulation or on real quantum hardware.')
parser.add_argument('--model', type=str, required=True,
                    help="The folder path of the QSVM model.")
parser.add_argument('--ntrain', type=int, default=600,
                    help='Number of training events for the QSVM.')
parser.add_argument('--ntest', type=int, default=720,
                    help='Number of test events for the QSVM.')
parser.add_argument('--kfolds', type=int, default=5,
                    help='Number of k-validation/test folds used.')
parser.add_argument('--nqubits', type=int, default=8,
                    help='Number of qubits for quantum feature map circuit.')
parser.add_argument('--output', type=str, required=True,
                    help='The name of the output .h5 file containing the scores,'
                         ' including the suffix ".h5".')
args = parser.parse_args()

# Load private configuration file for ibmq_api_token and provider details.   
try:
    with open('private_config_vasilis.json') as pconfig:
        private_configuration = json.load(pconfig)
except:
    print("Error in reading private config: Process aborted")

# Different configuration keyword arguments for the QuantumInstance depending 
# on the run_type. They can be tweaked as desired before running.
initial_layout = [1,2,3,5,8,11,14,16] # for Cairo

# TODO get these configs from a .json file with hyperparameters that is saved
# after the training in qsvm/main.py
seed = 12345
config_noisy = {'optimization_level':3, 'initial_layout': initial_layout,
                'seed_transpiler':seed, 'seed_simulator':seed, 'shots':5000}
config_hardware = {'optimization_level':3, 'initial_layout': initial_layout,
                   'seed_transpiler':seed, 'shots':5000}
config_ideal = {'seed_simulator': seed}

switcher = {'ideal' : lambda: config_ideal, 'noisy' : lambda: config_noisy, 
            'hardware' : lambda: config_hardware}
config = switcher.get(args.run_type, lambda: None)()

args = {
    "sig_path": args.sig_path,
    "bkg_path": args.bkg_path,
    "test_bkg_path": args.test_bkg_path,
    "backend_name": args.backend_name,
    "ibmq_api_config": private_configuration["IBMQ"],
    "run_type": args.run_type,
    "model": args.model,
    "config": config,
    "ntrain": args.ntrain,
    "ntest": args.ntest,
    "kfolds": args.kfolds,
    "seed": seed,
    "nqubits": args.nqubits,
    "output": args.output,
}

main(args)
